COIN.BIOM.Web/Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using System.IO;
using COIN.BIOM.Entity;
using COIN.BIOM.Entity.query;
using COIN.BIOM.Business;
using COIN.BIOM.Web.Models;
using BAZ.GEN.Log4Dan;

namespace COIN.BIOM.Web.Controllers
{
    [Authorize]
    public class ProcessController : Controller
    {

        private Log Log = new Log(typeof(ProcessController));
        private BLProcess oBLProcess;

        public ProcessController()
        {
            oBLProcess = new BLProcess();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string code = "", string name = "", int applicationId = 0)
        {
            List<ProcessList> lista = oBLProcess.List(code, name, applicationId);

            return Json(new { result = Enums.eCodeError.OK, data = lista }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListProcessUsersValids(string code = "", string name = "", int applicationId = 0)
        {
            List<ProcessUsersQuery> lista = oBLProcess.ListProcessUsersValids(code, name, applicationId);

            return Json(new { result = Enums.eCodeError.OK, data = lista }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListProcessUsers(string code = "", string name = "", int applicationId = 0)
        {
            List<ProcessUsersQuery> lista = oBLProcess.ListProcessUsers(code, name, applicationId);

            return Json(new { result = Enums.eCodeError.OK, data = lista }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DownloadListProcessUsers(string code = "", string name = "", int applicationId = 0)
        {
            try
            {
                string FileName = string.Format("ReportListProcessUsers_{0:ddMMyyyy_hhmm}.xlsx", DateTime.Now);

                string RutaPlantilla = Server.MapPath("~/Templates/TemplateListProcessUsers.xlsx");
                string RutaGuardarComo = Server.MapPath("~/Temporal/" + FileName);

                using (var pck = new OfficeOpenXml.ExcelPackage())
                {
                    using (var stream = System.IO.File.OpenRead(RutaPlantilla))
                    {
                        pck.Load(stream);
                    }

                    List<ProcessUsersQuery> lista = oBLProcess.ListProcessUsers(code, name, applicationId);

                    var ws = pck.Workbook.Worksheets["Data"];
                    int Fila = 2;
                    int Contador = 1;
                    foreach (ProcessUsersQuery itm in lista)
                    {
                        //Write process detail
                        ws.Cells[Fila, 1].Value = itm.processBussinessCode;
                        ws.Cells[Fila, 2].Value = itm.processName;
                        ws.Cells[Fila, 3].Value = itm.processDescription;
                        ws.Cells[Fila, 4].Value = itm.applicationBussinessCode;
                        ws.Cells[Fila, 5].Value = itm.applicationName;
                        ws.Cells[Fila, 6].Value = Contador;
                        ws.Cells[Fila, 7].Value = itm.userBussinessCode;
                        ws.Cells[Fila, 8].Value = itm.completeNameUser;
                        ws.Cells[Fila, 9].Value = itm.userName;
                        ws.Cells[Fila, 10].Value = itm.dni;
                        ws.Cells[Fila, 11].Value = itm.profileName;
                        ws.Cells[Fila, 12].Value = itm.email;
                        ws.Cells[Fila, 13].Value = string.Format("{0:dd/MM/yyyy HH:mm:ss}", itm.assignmentDate);
                        Fila++;
                        Contador++;
                    }

                    pck.SaveAs(new FileInfo(RutaGuardarComo));
                }

                return File(RutaGuardarComo, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);
            }
            catch (Exception ex)
            {
                Log.WriteLogError(ex.Message);
                return Content("No hay registros");
            }
        }

        public ActionResult Get(string id)
        {
            ProcessList item = oBLProcess.Get(id);

            return Json(new { result = Enums.eCodeError.OK, data = item }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Save(string processCode = "", string applicationBussinessCode = "", string processBussinessCode = "", string processName = "", int fingerprintQuantity = 0)
        {            
            BLApplication oBLApplication = new BLApplication();

            if (fingerprintQuantity <= 0)
            {
                return Json(new { result = Enums.eCodeError.ERROR, message = "Cantidad de Huellas ingresada es incorrecta." + applicationBussinessCode });
            }

            if (string.IsNullOrEmpty(processCode))
            {
                //Boton Nuevo Proceso --------------------------------------------------------------------------------------------
                //Validamos existencia de aplicación
                Application app = new Application();
                app.applicationBussinessCode = applicationBussinessCode;

                if (!oBLApplication.doValidateApplicationExists(app))
                {
                    return Json(new { result = Enums.eCodeError.ERROR, message = "No existe Aplicación con código " + applicationBussinessCode});
                }

                //Validamos la no existencia del proceso
                Process process = new Process();
                process.processBussinessCode = processBussinessCode;

                if (oBLProcess.doValidateProcessExists(process))
                {
                    return Json(new { result = Enums.eCodeError.ERROR, message = "Ya se registro un Proceso con el mismo Código" });
                }

                process.processName = processName;
                process.applicationBussinessCode = applicationBussinessCode;

                process.fingerprintQuantity = fingerprintQuantity;
                bool result = oBLProcess.Save(process);

                return Json(new { result = Enums.eCodeError.OK, message = "Guardado Satisfactoriamente" });

            }
            else {
                //Boton Editar Proceso --------------------------------------------------------------------------------------------

                Process process = new Process();
                process.processCode = processCode;
                process.processName = processName;
                process.fingerprintQuantity = fingerprintQuantity;

                bool result = oBLProcess.Edit(process);
                return Json(new { result = Enums.eCodeError.OK, message = "Actualizado Satisfactoriamente" });

            }
            
        }

        public ActionResult Delete(string id)
        {
            Process process = new Process();
            process.processCode = id;

            bool result = oBLProcess.Delete(process);

            return Json(new { result = Enums.eCodeError.OK, message = "Eliminado Satisfactoriamente" });
        }

        public ActionResult Nuevo()
        {
            UserProcessModel userProcessModel = new UserProcessModel();
            userProcessModel.processCode = "";
            userProcessModel.applicationBussinessCode = "";
            userProcessModel.processBussinessCode = "";
            userProcessModel.processName = "";
            return View("MantProcess",userProcessModel);
        }

        public ActionResult Edit(string processCode)
        {                        
            ProcessList item = oBLProcess.Get(processCode);

            UserProcessModel userProcessModel = new UserProcessModel();
            userProcessModel.processId = item.processId;
            userProcessModel.processCode = processCode;
            userProcessModel.processBussinessCode = item.processBussinessCode;
            userProcessModel.processName = item.processName;
            userProcessModel.processDescription = item.processDescription;
            userProcessModel.applicationId = item.applicationId;
            userProcessModel.applicationBussinessCode = item.applicationBussinessCode;
            userProcessModel.applicationName = item.applicationName;
            userProcessModel.processFingerprintQuantity = item.fingerprintQuantity;

            return View("MantProcess", userProcessModel);
        }



    }
}

COIN.BIOM.Web/Views/Process/Index.cshtml
@{
    ViewBag.Title = "Index";
    BLApplication BLApplication = new BLApplication();
    List<Application> aplicaciones = BLApplication.GetApplication();
}

@model ProcessModel

@using COIN.BIOM.Web.Models
@using COIN.BIOM.Entity
@using COIN.BIOM.Business

<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-info">
            <div class="box-header with-border">
                <center>
                    <h3 class="box-title">PROCESOS</h3>
                </center>
            </div>

            <!-- /.box-header -->
            <!-- form start -->
            <form id="frmBusqueda" action="@Url.Action("DownloadListProcessUsers", "Process")" method="get" class="form-horizontal" role="form">
                <div class="box-body">
                    <div class="form-group">
                        <label for="txtProcessBussinessCode" class="col-sm-2 control-label">Código Proceso</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtProcessBussinessCode" class="form-control" name="code" value="" maxlength="10"/>
                        </div>
                        <label for="ddlAplicacion" class="col-sm-2 control-label">Aplicación</label>
                        <div class="col-sm-3">
                            @Html.DropDownList("applicationId", new System.Web.Mvc.SelectList(aplicaciones, "applicationId", "applicationName"), "Seleccione", new { @class = "form-control", @id = "ddlAplicacion" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtProcessName" class="col-sm-2 control-label">Nombre Proceso</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtProcessName" class="form-control" name="name" maxlength="100" />
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <div class="col-sm-2" style="margin-left: 8% !important;">
                        <button id="btnBuscar" type="button" class="btn btn-primary">Buscar</button>
                    </div>
                    <div class="col-sm-2">
                        <a id="btnNuevo" class="btn btn-primary" href="@Url.Action("Nuevo")">Nuevo</a>
                    </div>
                    <div class="col-sm-3">
                        <button id="btnExportar" type="button" class="btn btn-success">Exportar Procesos - Excel</button>
                    </div>
                </div>
            </form>

            <div class="box-body">

                <table id="tabPrincipal" class="table table-bordered table-hover">
                    <thead>
                        <tr class="fondo-titulo-gris">
                            <th class="btnRow">

                            </th>
                            <th class="btnRow">

                            </th>
                            <th class="btnRow">

                            </th>
                            <th>
                                Código Proceso
                            </th>
                            <th>
                                Código
                            </th>
                            <th>
                                Proceso
                            </th>
                            <th>
                                Aplicación
                            </th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <!-- /.box -->
    </div>
</div>

@Html.Partial("_AddUserToProcess", new UserProcessModel())

@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="@Url.Content("~/Content/plugins/datatables/jquery.dataTables.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/plugins/datatables/dataTables.bootstrap.css")">

    <link href="@Url.Content("~/Content/plugins/jQueryConfirm/jquery-confirm.min.css")" rel="stylesheet" />

}

@section scripts{
    <!-- DataTables -->
    <script src="@Url.Content("~/Content/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/plugins/datatables/dataTables.bootstrap.min.js")"></script>

    <script src="@Url.Content("~/Content/plugins/jQueryValidate/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Content/plugins/jQueryValidate/localization/messages_es_PE.min.js")"></script>

    <script src="@Url.Content("~/Content/plugins/jQueryConfirm/jquery-confirm.min.js")"></script>

    <script src="@Url.Content("~/Scripts/app/process.js")"></script>

}

COIN.BIOM.Web/Views/Process/MantProcess.cshtml
@model UserProcessModel

@{
    ViewBag.Title = "MantProcess";
    
}

@using COIN.BIOM.Web.Models;
@using COIN.BIOM.Entity;
@using COIN.BIOM.Business;

<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- Default box -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title"> Mantenimiento Procesos </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <form id="frmBusqueda" class="form-horizontal" role="form">
                    <div class="form-group">
                        <input type="hidden" id="hdnProcessCode" class="form-control" name="processCode" value="@Model.processCode" />
                        <label for="txtApplicationBussinessCode" class="col-sm-2 control-label">Codigo Aplicación</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtApplicationBussinessCode" name="applicationBussinessCode" class="form-control" required="required" value="@Model.applicationBussinessCode" maxlength="10" />
                        </div>
                        <label for="txtProcessBussinessCode" class="col-sm-2 control-label">Código Proceso</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtProcessBussinessCode" name="processBussinessCode" class="form-control" required="required" value="@Model.processBussinessCode" maxlength="10" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtProcessName" class="col-sm-2 control-label">Nombre Proceso</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtProcessName" name="processName" class="form-control" required="required" value="@Model.processName" maxlength="100" />
                        </div>
                        <label for="fingerprintQuantity" class="col-sm-2 control-label">Cant. Huellas Requeridas</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtFingerprintQuantity" name="fingerprintQuantity" class="form-control soloEnteros" required="required" value="@Model.processFingerprintQuantity" maxlength="2" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-1">
                            <button id="btnGuardar" type="button" class="btn btn-primary">Guardar</button>
                        </div>
                        <div class="col-sm-1">
                            <a href="@Url.Action("Index", "Process")" class="btn btn-default">Regresar</a>
                        </div>
                    </div>
                </form>
            </div>
            <br />
            <div class="box-body">
                <form class="form-horizontal">
                    <div class="form-group" id="addUserBlock">
                        <label for="txtUserBussinessCode" class="col-sm-2 control-label">Código Usuario</label>
                        <div class="col-sm-3">
                            <input type="text" id="txtUserBussinessCode" name="userBussinessCode" class="form-control" required="required" maxlength="10" />
                        </div>
                        <div class="col-sm-3">
                            <button id="btnAsignarUsuario" type="button" class="btn btn-primary">Asignar Usuario</button>
                        </div>
                    </div>                    
                </form>
            </div>
            <br />
            <div class="box-body">
                <h3>Detalle Usuarios</h3>
                <table id="tabPrincipal" class="table table-bordered table-hover">
                    <thead>
                        <tr class="fondo-titulo-gris">
                            <th>

                            </th>
                            <th>
                                Código Usuario(userCode)
                            </th>
                            <th>
                                Código Proceso(processCode)
                            </th>
                            <th>
                                Código Usuario
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Dni
                            </th>
                            <th>
                                Proceso
                            </th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
        <!-- /.box -->
    </div>
</div>

@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="@Url.Content("~/Content/plugins/datatables/jquery.dataTables.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/plugins/datatables/dataTables.bootstrap.css")">

    <link href="@Url.Content("~/Content/plugins/jQueryConfirm/jquery-confirm.min.css")" rel="stylesheet" />

}

@section scripts{
    <!-- DataTables -->
    <script src="@Url.Content("~/Content/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/plugins/datatables/dataTables.bootstrap.min.js")"></script>

    <script src="@Url.Content("~/Content/plugins/jQueryValidate/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Content/plugins/jQueryValidate/localization/messages_es_PE.min.js")"></script>

    <script src="@Url.Content("~/Content/plugins/jQueryConfirm/jquery-confirm.min.js")"></script>

    <script src="@Url.Content("~/Scripts/app/mantProcessUser.js")"></script>

}

COIN.BIOM.Web/Views/Process/_AddUserToProcess.cshtml
@{
    BLProfile BLProfile = new BLProfile();
    List<Profile> perfiles = BLProfile.GetProfile();
}

@model UserProcessModel

@using COIN.BIOM.Web.Models
@using COIN.BIOM.Entity
@using COIN.BIOM.Business;


<div id="divPrincipal" class="modal fade" role="dialog">
    <form id="frmPrincipal" class="form-horizontal">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Agregar Usuarios</h4>
                </div>
                <div class="modal-body">
                    <div class="box-body">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Perfil </label>
                            <div class="col-sm-9">
                                @Html.DropDownListFor(p => p.profileId, new System.Web.Mvc.SelectList(perfiles, "profileId", "name"), "Seleccione", new { @class = "form-control", @id = "ddlPerfilMantUserInProcess", @required = "required" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.HiddenFor(p => p.processCode, new { @id = "hdnProcessCode", @name= "processCode" })
                            @Html.HiddenFor(p => p.userCode, new { @id = "hdnUserCode", @name = "userCode" })
                            <label class="col-sm-3 control-label"> Código Usuario </label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(p => p.userBussinessCode, new { @class = "form-control", @required = "required", @id = "txtUserBussinessCodeMantUserInProcess", @maxlength = "10" })
                            </div>
                        </div>
                        <div class="form-group" id="divUsernameMantUserInProcess">
                            <label class="col-sm-3 control-label"> Nombre de Usuario </label>
                            <div class="col-sm-9">
                                <input type="text" name="userName" id="txtUserNameMantUserInProcess" class="form-control" value="" maxlength="50" />
                            </div>
                        </div>
                        <div class="form-group" id="divPassMantUserInProcess">
                            <label class="col-sm-3 control-label"> Contraseña </label>
                            <div class="col-sm-9">
                                <input type="password" name="password" id="txtPasswordMantUserInProcess" class="form-control" value="" maxlength="50" />
                            </div>
                        </div>
                        <div class="form-group" id="divConfirmPassMantUserInProcess">
                            <label class="col-sm-3 control-label"> Confirmar Contraseña </label>
                            <div class="col-sm-9">
                                <input type="password" name="confirmPassword" id="txtConfirmPasswordMantUserInProcess" class="form-control" value="" maxlength="50" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Nombres </label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(p => p.name, new { @class = "form-control", @required = "required", @id = "txtNameMantUserInProcess", @maxlength = "50" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Apellidos </label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(p => p.lastName, new { @class = "form-control", @required = "required", @id = "txtLastNameMantUserInProcess", @maxlength = "50" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Correo Electrónico </label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" id="txtEmailMantUserInProcess" name="email" maxlength="80" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Dni </label>
                            <div class="col-sm-9">
                                <!--<input type="number" name="dni" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" class="form-control" required="required" id="txtDniMantUserInProcess" maxlength="8" />-->
                                <input type="text" name="dni" class="form-control soloEnteros" required="required" id="txtDniMantUserInProcess" maxlength="8" />
                            </div>
                        </div>                        
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> Proceso </label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(p => p.processName, new { @class = "form-control", @required = "required", @id = "txtProcessNameMantUserInProcess" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnGuardar" type="button" class="btn btn-primary">Guardar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>

        </div>
    </form>
</div>