COIN.BIOM.Web/Controllers/EventualityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using COIN.BIOM.Entity.query;
using COIN.BIOM.Business;
using COIN.BIOM.Web.Models;
using System.Globalization;
using System.IO;
using BAZ.GEN.Log4Dan;

namespace COIN.BIOM.Web.Controllers
{
    [Authorize]
    public class EventualityController : Controller
    {
        private Log Log = new Log(typeof(EventualityController));
        private BLEventuality oBLEventuality;

        public EventualityController()
        {
            oBLEventuality = new BLEventuality();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DownloadListEventuality(String date1 = "", String date2 = "", int processFilter = 0, int applicationFilter = 0)
        {
            DateTime? CDate1 = null;
            DateTime? CDate2 = null;

            try
            {
                string FileName = string.Format("ReportListEventualities_{0:ddMMyyyy_hhmm}.xlsx", DateTime.Now);

                string RutaPlantilla = Server.MapPath("~/Templates/TemplateListEventuality.xlsx");
                string RutaGuardarComo = Server.MapPath("~/Temporal/" + FileName);

                CDate1 = DateTime.ParseExact(date1, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                CDate2 = DateTime.ParseExact(date2, "dd/MM/yyyy", CultureInfo.InvariantCulture);

                using (var pck = new OfficeOpenXml.ExcelPackage())
                {
                    using (var stream = System.IO.File.OpenRead(RutaPlantilla))
                    {
                        pck.Load(stream);
                    }

                    List<EventlogQuery> lista = oBLEventuality.GetEventlogsByParams(CDate1, CDate2, processFilter, applicationFilter);

                    var ws = pck.Workbook.Worksheets["Data"];
                    int Fila = 2;
                    int Contador = 1;
                    foreach (EventlogQuery itm in lista)
                    {
                        ws.Cells[Fila, 1].Value = Contador;
                        ws.Cells[Fila, 2].Value = itm.userBussinessCode;
                        ws.Cells[Fila, 3].Value = itm.userName;
                        ws.Cells[Fila, 4].Value = itm.completeName;
                        ws.Cells[Fila, 5].Value = itm.profileName;
                        ws.Cells[Fila, 6].Value = itm.dni;
                        ws.Cells[Fila, 7].Value = itm.email;
                        ws.Cells[Fila, 8].Value = itm.userState;
                        ws.Cells[Fila, 9].Value = itm.applicationBussinessCode;
                        ws.Cells[Fila, 10].Value = itm.applicationName;
                        ws.Cells[Fila, 11].Value = itm.processBussinessCode;
                        ws.Cells[Fila, 12].Value = itm.processName;
                        ws.Cells[Fila, 13].Value = string.Format("{0:dd/MM/yyyy HH:mm:ss}", itm.eventlogDatatime);                        
                        ws.Cells[Fila, 14].Value = itm.eventlogResult;
                        Fila++;
                        Contador++;
                    }

                    pck.SaveAs(new FileInfo(RutaGuardarComo));
                }

                return File(RutaGuardarComo, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);
            }
            catch (Exception ex)
            {
                Log.WriteLogError(ex.Message);
                return Content("No hay registros");
            }
        }





    }
}

COIN.BIOM.Web/Views/Eventuality/Index.cshtml
@{
    ViewBag.Title = "Index";
    string CFecha = string.Format("{0:dd/MM/yyyy}", DateTime.Today);
    BLApplication BLApplication = new BLApplication();
    BLProcess BLProcess = new BLProcess();
    BLUser oBLUser = new BLUser();
    
    List<ProcessList> procesos = BLProcess.List("", "", 0);
    List<Application> aplicaciones = BLApplication.GetApplication();
    
    User item = oBLUser.Get(WebSecurity.CurrentUserName);
}

@using System.Configuration
@using COIN.BIOM.Web.Models
@using COIN.BIOM.Entity
@using COIN.BIOM.Business

<div class="row">
    <div class="col-md-10">
        <div class="box box-info">
            <div class="box-header with-border">
                <center>
                    <h3 class="box-title">CONSULTA DE EVENTUALIDADES</h3>
                </center>
            </div>

            <form id="frmBusqueda" class="form-horizontal" role="form" method="get" action="@Url.Action("DownloadListEventuality", "Eventuality")">
                <!--<input type="hidden" id="hdnUrlImagenes"  />-->
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Fecha Desde</label>
                        <div class="col-sm-3">
                            <input type="hidden" id="hdnFechaDesde" class="form-control" name="date1" />
                            <div class="input-group date dateTimePicker">
                                <input type="text" class="form-control pull-right" id="txtFechaDesde" value="@CFecha">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                            </div>
                        </div>
                        <label for="inputEmail3" class="col-sm-2 control-label">Fecha Hasta</label>
                        <div class="col-sm-3">
                            <input type="hidden" id="hdnFechaHasta" class="form-control" name="date2" />
                            <div class="input-group date dateTimePicker">
                                <input type="text" class="form-control pull-right" id="txtFechaHasta" value="@CFecha">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <!--
                        <input type="hidden" id="hdnCodCli" class="form-control" name="codcli"  />
                        <input type="hidden" id="hdnPerfil" class="form-control" name="idperfil"  />                     -->   
                        <label for="inputEmail3" class="col-sm-2 control-label">Procesos</label>
                        <div class="col-sm-3">
                            @Html.DropDownList("processFilter", new System.Web.Mvc.SelectList(procesos, "processId", "processName"), "Seleccione", new { @class = "form-control", @id = "ddlProceso" })
                        </div>                        
                        <label for="inputEmail3" class="col-sm-2 control-label">Aplicaciones</label>
                        <div class="col-sm-3">
                            @Html.DropDownList("applicationFilter", new System.Web.Mvc.SelectList(aplicaciones, "applicationId", "applicationName"), "Seleccione", new { @class = "form-control", @id = "ddlApplication" })
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <!--
                    <div class="col-sm-1">
                        <button id="btnBuscar" type="button" class="btn btn-primary">Buscar</button>
                    </div> -->
                    <div class="col-sm-2" style="margin-left: 7% !important;">
                        <button id="btnExportar" type="button" class="btn btn-success">Exportar</button>
                    </div>
                </div>
            </form>
            <!--
            <div class="box-body">
                <table id="tabPrincipal" class="table table-bordered table-hover">
                    <thead>
                        <tr class="fondo-titulo-gris">
                            <th>
                                Id
                            </th>
                            <th>
                                Code
                            </th>
                            <th>
                                Fecha Hora
                            </th>
                            <th>
                                Tipo Incidente
                            </th>
                            <th>
                                Sub Tipo Incidente
                            </th>
                            <th>
                                Lugar
                            </th>
                            <th>
                                Nivel de Criticidad
                            </th>
                            <th>
                                Nombres
                            </th>
                            <th>
                                Apellidos
                            </th>
                            <th>
                                Fecha Creación
                            </th>
                            <th>
                                Cliente
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>

                -->
        </div>
    </div>
</div>



@section styles{
    <!-- DataTables -->
    <link rel="stylesheet" href="@Url.Content("~/Content/plugins/datatables/jquery.dataTables.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/plugins/datatables/dataTables.bootstrap.css")">

    <link href="@Url.Content("~/Content/plugins/magnificPopup/magnific-popup.css")" rel="stylesheet" />

}

@section scripts{
    <!-- DataTables -->
    <script src="@Url.Content("~/Content/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/plugins/datatables/dataTables.bootstrap.min.js")"></script>

    <script src="@Url.Content("~/Content/plugins/magnificPopup/magnific-popup.js")"></script>

    <script src="@Url.Content("~/Scripts/app/eventuality.js")"></script>

}